Description: 
  Definition of the public facing Application Load Balancer

Parameters:

  Environment: 
    Description: Choose the environment 
    ConstraintDescription: Select one option from the drop down menu
    Type: String 
    Default: dev
    AllowedValues:
      - dev
      - stg 
      - prod

Resources:

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${Environment}-alb
      Scheme: internet-facing
      Subnets: 
        - Fn::ImportValue:
            !Sub ${Environment}-private-subnetA
        - Fn::ImportValue:
            !Sub ${Environment}-private-subnetB
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: 30
  
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - ALB
      - ALBTargetGroup
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${Environment}-target-group
      HealthCheckIntervalSeconds: 6
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: 
        Fn::ImportValue:
          !Sub ${Environment}-vpc

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the public facing load balancer
      VpcId: 
        Fn::ImportValue:
          !Sub ${Environment}-vpc
      SecurityGroupIngress:
          - CidrIp: 0.0.0.0/0
            IpProtocol: -1

Outputs:
  ALBDNSName:
    Description: Application Load Balancer DNS name
    Value: !GetAtt ALB.DNSName

  ALBSecurityGroup:
    Description: Application Load Balancer security group
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub ${Environment}-alb-sg

  ALBTargetGroupFullName:
    Description: Application Load Balancer target group
    Value: !GetAtt ALBTargetGroup.TargetGroupFullName
    Export:
      Name: !Sub ${Environment}-alb-target-group-full-name

  ALBTargetGroupArn:
    Description: Application Load Balancer target group Arn
    Value: !Ref ALBTargetGroup
    Export:
      Name: !Sub ${Environment}-alb-target-group-arn